// example/react/code.js
import React, {useEffect, useRef} from "react";
import hljs from 'highlight.js'
import 'highlight.js/styles/lightfair.css'

export default function Code(props){

  const refCode = useRef(null)

  useEffect(()=>{
    hljs.highlightElement(refCode.current);
  }, [])

  return (
    <pre><code ref={refCode}>{props.content}</code></pre>
  )
}

// example/vue/code.vue
<template>
  <pre><code ref="refCode">{{content}}</code></pre>
</template>

<script setup>
import {ref, defineProps, onMounted} from "vue";
import hljs from 'highlight.js'
import 'highlight.js/styles/lightfair.css'

defineProps({
  content: String
})
const refCode = ref(null)
onMounted(()=>{
  hljs.highlightElement(refCode.value)
})
</script>

<style scoped>

</style>
